version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gateway_db
    restart: always
    environment:
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_password
      POSTGRES_DB: gateway_router
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
